language: python

# Setting sudo to false opts in to Travis-CI container-based builds.
sudo: false

python:
    - 2.7
    - 3.5

addons:
    apt:
        packages:
            # Used for Spginx 
            - graphviz
            - texlive-latex-extra
            - dvipng

env:
    global:
        # The following versions are the 'default' for tests, unless
        # overidden underneath. They are defined here in order to save having
        # to repeat them for all configurations.
        - NUMPY_VERSION=1.11
        - OLDER_NUMPY_VERSION=1.10
        - ASTROPY_VERSION=stable
        - CONDA_INSTALL='conda install --yes'
        - PIP_INSTALL='pip install'
    matrix:
        - SETUP_CMD='egg_info'

matrix:
    include:
        # Do a coverage test in Python 3.
        - python: 3.5
          env: SETUP_CMD='test --coverage'

        # Check for sphinx doc build errors
        - python: 3.5
          env: SETUP_CMD='build_sphinx'

        # Try all supported Python versions with the latest NumPy
        # and other dependencies
        - python: 2.7
          env: SETUP_CMD='test'
        - python: 3.5
          env: SETUP_CMD='test'

        # Try Astropy development version
        - python: 3.5
          env: ASTROPY_VERSION=development SETUP_CMD='test'

        # Test one previous version of NumPy
        - python: 2.7
          env: NUMPY_VERSION=$OLDER_NUMPY_VERSION ASTROPY_VERSION=stable SETUP_CMD='test'

before_install:

    # Use utf8 encoding. Should be default, but this is insurance against
    # future changes
    - export PYTHONIOENCODING=UTF8
    # Prefer Agg backend in case PyPlot is imported
    # (see http://matplotlib.org/faq/environment_variables_faq.html)
    - export MPLBACKEND=Agg
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - ./miniconda.sh -b
    - export PATH=/home/travis/miniconda2/bin:$PATH
    - conda update --yes conda

install:

    # CONDA
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test

    # CORE DEPENDENCIES
    - $CONDA_INSTALL numpy=$NUMPY_VERSION pytest pip Cython jinja2
    - $PIP_INSTALL pytest-xdist

    # ASTROPY
    - if [[ $ASTROPY_VERSION == development ]]; then $PIP_INSTALL git+http://github.com/astropy/astropy.git#egg=astropy; fi
    - if [[ $ASTROPY_VERSION == stable ]]; then $CONDA_INSTALL numpy=$NUMPY_VERSION astropy; fi

    # OPTIONAL DEPENDENCIES
    # Here you can add any dependencies your package may have. You can use
    # conda for packages available through conda, or pip for any other
    # packages. You should leave the `numpy=$NUMPY_VERSION` in the `conda`
    # install since this ensures Numpy does not get automatically upgraded.
    - if [[ $SETUP_CMD != egg_info ]]; then $CONDA_INSTALL numpy=$NUMPY_VERSION matplotlib scipy; fi
    - if [[ $SETUP_CMD != egg_info ]]; then $PIP_INSTALL six enum34; fi

    # DOCUMENTATION DEPENDENCIES
    # build_sphinx needs sphinx and matplotlib (for plot_directive). Note that
    # this matplotlib will *not* work with py 3.x, but our sphinx build is
    # currently 2.7, so that's fine
    - if [[ $SETUP_CMD == build_sphinx* ]]; then $CONDA_INSTALL numpy=$NUMPY_VERSION Sphinx matplotlib; fi

    # COVERAGE DEPENDENCIES
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then $PIP_INSTALL coverage coveralls; fi

script:
    - python setup.py $SETUP_CMD

after_success:
    # If coveralls.io is set up for this package, uncomment the line
    # below and replace "packagename" with the name of your package.
    # The coveragerc file may be customized as needed for your package.
    - if [[ $SETUP_CMD == 'test --coverage' ]]; then coveralls --rcfile='poppy/tests/coveragerc'; fi

notifications:
    email:
        - mperrin@stsci.edu
        - jlong@stsci.edu
