package:
  name: poppy
  version: "0.3.5"

source:
  git_tag: "v0.3.5"
  git_url: https://github.com/mperrin/poppy.git

requirements:
  build:
    - python 2.7*|3.4*
    - setuptools
    - mock
    - nose
    - numpy >=1.8,<2
    - matplotlib >=1.3
    - scipy >=0.14
    - astropy >=1.0
    - six >=1.7.3

  run:
    - python 2.7*|3.4*
    - numpy >=1.8,<2
    - matplotlib >=1.3
    - scipy >=0.14
    - astropy >=1.0
    - six >=1.7.3

test:
  imports:
    - poppy

about:
  home: http://pythonhosted.org/poppy/
  license: BSD
  summary: "POPPY simulates Physical Optical Propagation in Python."
